from __future__ import annotations  
  
import json  
import sys  
import tempfile  
from pathlib import Path  
  
# Ensure repo root is on sys.path when running from dev/  
PROJECT_ROOT = Path(__file__).resolve().parents[1]  
if str(PROJECT_ROOT) not in sys.path:  
    sys.path.insert(0, str(PROJECT_ROOT))  
  
from BUILD.build_1a_workflow_generator import generate_workflow  # noqa: E402  
  
  
def _load_registry_actions() -> tuple[set[str], dict]:  
    reg_path = PROJECT_ROOT / "REGISTRY" / "action_registry.json"  
    reg = json.loads(reg_path.read_text(encoding="utf-8"))  
    if not isinstance(reg, dict):  
        return set(), {}  
  
    actions = reg.get("actions")  
  
    # Shape A: {"actions": {"get": {...}, ...}}  
    if isinstance(actions, dict):  
        return set(actions.keys()), reg  
  
    # Shape B (your current file): {"actions": [{"action": "get", ...}, ...]}  
    if isinstance(actions, list):  
        names: set[str] = set()  
        for item in actions:  
            if not isinstance(item, dict):  
                continue  
            a = item.get("action") or item.get("name")  
            if isinstance(a, str) and a.strip():  
                names.add(a.strip())  
        return names, reg  
  
    # Shape C: flat mapping (fallback)  
    blacklist = {"generated_at_utc", "generated_at", "version", "schema_version", "meta", "__meta__", "actions"}  
    return {k for k in reg.keys() if k not in blacklist}, reg  
  
  
def _action_meta(registry: dict, action: str) -> dict | None:  
    actions = registry.get("actions")  
  
    if isinstance(actions, dict):  
        meta = actions.get(action)  
        return meta if isinstance(meta, dict) else None  
  
    if isinstance(actions, list):  
        for item in actions:  
            if not isinstance(item, dict):  
                continue  
            a = item.get("action") or item.get("name")  
            if a == action:  
                return item  
        return None  
  
    meta = registry.get(action)  
    return meta if isinstance(meta, dict) else None  
  
  
def _required_fields_for_action(registry: dict, action: str) -> list[str]:  
    meta = _action_meta(registry, action)  
    if not isinstance(meta, dict):  
        return []  
  
    # Your registry uses required_fields/optional_fields  
    for k in ("required_fields", "required", "requires"):  
        v = meta.get(k)  
        if isinstance(v, list):  
            return [str(x) for x in v if isinstance(x, (str, int, float))]  
  
    # Optional alternate shape: args with required: true  
    args = meta.get("args")  
    if isinstance(args, dict):  
        req = []  
        for name, spec in args.items():  
            if isinstance(spec, dict) and spec.get("required") is True:  
                req.append(str(name))  
        return req  
  
    return []  
  
  
def _fill_required_fields(step: dict, required: list[str]) -> dict:  
    out = dict(step)  
    for f in required:  
        if f in out and out.get(f) not in (None, ""):  
            continue  
        if f == "url":  
            out[f] = "https://example.com/"  
        elif f == "script_path":  
            out[f] = "scripts/noop.js"  
        elif f in ("text", "value", "contains", "equals"):  
            out[f] = "SMOKE"  
        elif f == "selector_ref":  
            out[f] = "TODO_SMOKE_SELECTOR"  
        else:  
            out[f] = "TODO"  
    return out  
  
  
def main() -> int:  
    actions, registry = _load_registry_actions()  
    assert actions, "No actions found in REGISTRY/action_registry.json"  
  
    preferred = ["get", "assert", "js", "javascript", "wait"]  
    chosen = [a for a in preferred if a in actions]  
    if not chosen:  
        chosen = [sorted(actions)[0]]  
  
    steps = []  
    for a in chosen[:2]:  
        step = {"action": a}  
  
        # Even if registry only requires ["action"], it's still fine to include url for "get"  
        req = _required_fields_for_action(registry, a)  
        step = _fill_required_fields(step, req)  
        if a == "get" and "url" not in step:  
            step["url"] = "https://example.com/"  
  
        steps.append(step)  
  
    spec = {  
        "name": "smoke_build_1a",  
        "intent": "BUILD-1A smoke test",  
        "entry_url": "https://example.com/",  
        "headless": True,  
        "inputs": {"mode": "none"},  
        "steps": steps,  
        "outputs": {"downloads": False},  
        "notes": ["Generated by dev_smoke_build_1a.py"],  
        # keep deterministic output  
        "created_at_utc": "1970-01-01T00:00:00Z",  
    }  
  
    with tempfile.TemporaryDirectory() as td:  
        out_dir = Path(td)  
        result = generate_workflow(spec, output_dir=out_dir, overwrite=True)  
  
        assert result["ok"] is True, f"generate_workflow failed:\n{json.dumps(result, indent=2)}"  
        wf_path = Path(result["workflow_path"])  
        assert wf_path.exists(), f"workflow file not created: {wf_path}"  
  
        obj = json.loads(wf_path.read_text(encoding="utf-8"))  
        assert isinstance(obj, dict)  
        assert isinstance(obj.get("metadata"), dict)  
        assert obj["metadata"].get("generator") == "BUILD-1A"  
        assert "created_at_utc" in obj["metadata"]  
        assert isinstance(obj.get("steps"), list)  
  
        print("PASS: BUILD-1A")  
        print(f"workflow_path: {wf_path}")  
        print("actions_used:", result["summary"]["actions_used"])  
  
    return 0  
  
  
if __name__ == "__main__":  
    raise SystemExit(main())  